[project]
name = "fish-stocking-analysis"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.16.5",
    "matplotlib==3.10.7",
    "numpy>=2.3.3",
    "pandas==2.3.3",
    "scipy==1.16.3",
    "tabulate==0.9.0",
]
